/**
 * @sportiq/media — ClipSignature engine.
 *
 * A ClipSignature is a content-addressable identity for a clip.
 * Two clip requests with identical parameters produce the same sig_hash,
 * allowing the render system to skip re-rendering and serve cached assets.
 *
 * Hash inputs:
 *   video_asset_id + start_sec (3dp) + end_sec (3dp) + overlays (sorted + serialized)
 *
 * Implementation: SHA-256 via Web Crypto API (available in browsers, Deno, Node 18+).
 * For environments without SubtleCrypto, a pure-JS fallback is provided.
 */

import type { ClipSignature, OverlaySpec } from '../types/index';

// ─── Hash computation ─────────────────────────────────────────────────────────

interface HashInput {
  videoAssetId: string;
  startSec:     number;
  endSec:       number;
  overlays:     OverlaySpec[];
}

/**
 * Serialize hash inputs into a stable, canonical string.
 * Overlays are sorted by frame_sec then type to ensure order-independence.
 */
function canonicalize(input: HashInput): string {
  const sortedOverlays = [...input.overlays].sort((a, b) => {
    if (a.frame_sec !== b.frame_sec) return a.frame_sec - b.frame_sec;
    return a.type.localeCompare(b.type);
  });

  return JSON.stringify({
    v:  input.videoAssetId,
    s:  input.startSec.toFixed(3),
    e:  input.endSec.toFixed(3),
    o:  sortedOverlays,
  });
}

/**
 * Compute a SHA-256 hash for a ClipSignature.
 * Returns a hex string.
 *
 * Uses SubtleCrypto if available (browser/Deno/Node 18+),
 * falls back to a djb2-based non-cryptographic hash for environments
 * where Web Crypto is unavailable (e.g. older Jest environments).
 */
export async function computeSigHash(input: HashInput): Promise<string> {
  const canonical = canonicalize(input);

  if (typeof crypto !== 'undefined' && crypto.subtle) {
    const encoded = new TextEncoder().encode(canonical);
    const hashBuffer = await crypto.subtle.digest('SHA-256', encoded);
    return Array.from(new Uint8Array(hashBuffer))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
  }

  // Fallback: djb2 (non-cryptographic, only for environments without SubtleCrypto)
  return djb2Hash(canonical);
}

function djb2Hash(str: string): string {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash) ^ str.charCodeAt(i);
    hash = hash >>> 0; // keep 32-bit unsigned
  }
  return hash.toString(16).padStart(8, '0');
}

// ─── ClipSignature builder ────────────────────────────────────────────────────

export interface CreateClipSignatureParams {
  id:             string;   // UUID, generated by caller
  videoAssetId:   string;
  startSec:       number;
  endSec:         number;
  overlays?:      OverlaySpec[];
}

export async function buildClipSignature(
  params: CreateClipSignatureParams,
): Promise<Omit<ClipSignature, 'created_at'>> {
  const overlays = params.overlays ?? [];
  const sig_hash = await computeSigHash({
    videoAssetId: params.videoAssetId,
    startSec:     params.startSec,
    endSec:       params.endSec,
    overlays,
  });

  return {
    id:             params.id,
    video_asset_id: params.videoAssetId,
    sig_hash,
    start_sec:      params.startSec,
    end_sec:        params.endSec,
    overlays,
  };
}

// ─── Duration guard ───────────────────────────────────────────────────────────

export interface ValidationResult {
  valid:   boolean;
  errors:  string[];
}

export function validateClipBounds(
  startSec:       number,
  endSec:         number,
  videoDuration?: number,
): ValidationResult {
  const errors: string[] = [];

  if (startSec < 0)             errors.push('start_sec cannot be negative');
  if (endSec <= startSec)       errors.push('end_sec must be greater than start_sec');
  if (endSec - startSec < 0.5)  errors.push('clip duration must be at least 0.5 seconds');
  if (endSec - startSec > 3600) errors.push('clip duration exceeds 1 hour');

  if (videoDuration != null) {
    if (endSec > videoDuration)
      errors.push(`end_sec (${endSec}) exceeds video duration (${videoDuration})`);
  }

  return { valid: errors.length === 0, errors };
}

// ─── Timeline composition helpers ────────────────────────────────────────────

/**
 * Lay out clips sequentially with an optional gap between them.
 * Returns clips with computed start_in_timeline / end_in_timeline.
 */
export interface ClipLayout {
  id:                  string;
  source_start:        number;
  source_end:          number;
  start_in_timeline:   number;
  end_in_timeline:     number;
  duration:            number;
}

export function layoutClips(
  clips: Array<{ id: string; source_start: number; source_end: number }>,
  gapSeconds = 0,
): ClipLayout[] {
  let cursor = 0;
  return clips.map((c) => {
    const duration = c.source_end - c.source_start;
    const layout: ClipLayout = {
      id:               c.id,
      source_start:     c.source_start,
      source_end:       c.source_end,
      start_in_timeline: cursor,
      end_in_timeline:   cursor + duration,
      duration,
    };
    cursor += duration + gapSeconds;
    return layout;
  });
}

/**
 * Total duration of a composed timeline.
 */
export function timelineDuration(layouts: ClipLayout[]): number {
  if (layouts.length === 0) return 0;
  return layouts[layouts.length - 1]!.end_in_timeline;
}
